/* Generated By:JavaCC: Do not edit this line. TranslationUnitTokenManager.java */
package br.edu.ufcg.symbolrt.compiler.parser;

/** Token Manager. */
public class TranslationUnitTokenManager implements TranslationUnitConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8000000L) != 0L)
            return 6;
         if ((active0 & 0x3cffff2601f80L) != 0L)
         {
            jjmatchedKind = 53;
            return 17;
         }
         return -1;
      case 1:
         if ((active0 & 0x1cafff0601f80L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 53;
               jjmatchedPos = 1;
            }
            return 18;
         }
         if ((active0 & 0x2050002000000L) != 0L)
            return 18;
         return -1;
      case 2:
         if ((active0 & 0x1cafdf0001780L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 53;
               jjmatchedPos = 2;
            }
            return 18;
         }
         if ((active0 & 0x200600800L) != 0L)
            return 18;
         return -1;
      case 3:
         if ((active0 & 0xc09fe0000380L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 3;
            return 18;
         }
         if ((active0 & 0x10a6010001400L) != 0L)
            return 18;
         return -1;
      case 4:
         if ((active0 & 0x409740000280L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 4;
            return 18;
         }
         if ((active0 & 0x8008a0000100L) != 0L)
            return 18;
         return -1;
      case 5:
         if ((active0 & 0x409640000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 5;
            return 18;
         }
         if ((active0 & 0x100000280L) != 0L)
            return 18;
         return -1;
      case 6:
         if ((active0 & 0x409600000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 6;
            return 18;
         }
         if ((active0 & 0x40000000L) != 0L)
            return 18;
         return -1;
      case 7:
         if ((active0 & 0x401400000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 7;
            return 18;
         }
         if ((active0 & 0x8200000000L) != 0L)
            return 18;
         return -1;
      case 8:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 8;
            return 18;
         }
         if ((active0 & 0x400400000000L) != 0L)
            return 18;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 45);
      case 37:
         return jjStopAtPos(0, 26);
      case 40:
         return jjStopAtPos(0, 51);
      case 41:
         return jjStopAtPos(0, 50);
      case 42:
         return jjStopAtPos(0, 24);
      case 43:
         return jjStopAtPos(0, 23);
      case 44:
         return jjStopAtPos(0, 58);
      case 45:
         return jjStopAtPos(0, 20);
      case 47:
         return jjStartNfaWithStates_0(0, 27, 6);
      case 58:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x10000000000000L);
      case 59:
         return jjStopAtPos(0, 57);
      case 60:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0xe0000L);
      case 61:
         return jjStopAtPos(0, 15);
      case 62:
         jjmatchedKind = 13;
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 63:
         return jjStopAtPos(0, 44);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x300L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x2408000000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x42280000800L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x80800000080L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x11000000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 123:
         return jjStopAtPos(0, 60);
      case 124:
         return jjStopAtPos(0, 61);
      case 125:
         return jjStopAtPos(0, 62);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(1, 14);
         else if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 62:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 82:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 25, 18);
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800400000400L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x408000000000L);
      case 102:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 42, 18);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2280000800L);
      case 111:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 40, 18);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 49, 18);
         return jjMoveStringLiteralDfa2_0(active0, 0x1100L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x5040000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000080L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(2, 19);
         break;
      case 68:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 18);
         break;
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 84:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 18);
         break;
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x9800000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000100L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040001200L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 116:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x300000400L);
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 18);
         break;
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 99:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x40000200L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x800200000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 108:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 18);
         break;
      case 109:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 38, 18);
         break;
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 41, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 116:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 18);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000080L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 121:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 48, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 18);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L);
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 18);
         return jjMoveStringLiteralDfa5_0(active0, 0x40000080L);
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 114:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 18);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L);
      case 116:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 18);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 18);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x9000000000L);
      case 109:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 7, 18);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
      case 115:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 9, 18);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 116:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L);
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000L);
      case 115:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 18);
         break;
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 39, 18);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000L);
      case 108:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(7, 33, 18);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 46, 18);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000L);
      case 115:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(8, 34, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 36, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 17;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     jjCheckNAdd(4);
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 1);
                  break;
               case 17:
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(2, 1);
                  break;
               case 6:
                  if (curChar == 47)
                     jjCheckNAddStates(2, 4);
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(2, 1);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAdd(4);
                  break;
               case 5:
                  if (curChar == 47)
                     jjAddStates(0, 1);
                  break;
               case 7:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 8:
                  if (curChar == 42)
                     jjCheckNAddStates(5, 7);
                  break;
               case 9:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(10, 8);
                  break;
               case 10:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(10, 8);
                  break;
               case 11:
                  if (curChar == 47 && kind > 5)
                     kind = 5;
                  break;
               case 12:
                  if (curChar == 47)
                     jjCheckNAddStates(2, 4);
                  break;
               case 13:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 14:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 15:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 16:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 17:
               case 3:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(8, 10);
                  break;
               case 18:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAddStates(8, 10);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAddTwoStates(2, 1);
                  }
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(2, 1);
                  break;
               case 7:
                  jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
               case 10:
                  jjCheckNAddTwoStates(10, 8);
                  break;
               case 13:
                  jjAddStates(2, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(10, 8);
                  break;
               case 13:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(2, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 17 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   6, 12, 13, 14, 16, 8, 9, 11, 2, 1, 3, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\163\171\163\164\145\155", 
"\143\157\156\163\164", "\143\154\157\143\153\163", "\147\141\164\145", "\151\156\164", 
"\142\157\157\154", "\76", "\76\75", "\75", "\74", "\74\75", "\74\76", "\74\75\76", "\55", 
"\116\117\124", "\101\116\104", "\53", "\52", "\117\122", "\45", "\57", "\124\122\125\105", 
"\106\101\114\123\105", "\160\162\157\143\145\163\163", "\151\156\160\165\164", 
"\157\165\164\160\165\164", "\151\156\164\145\162\156\141\154", "\166\141\162\151\141\142\154\145\163", 
"\163\164\141\164\145", "\164\162\141\156\163\151\164\151\157\156", "\151\156\151\164", 
"\146\162\157\155", "\144\145\141\144\154\151\156\145", "\164\157", "\167\150\145\156", 
"\151\146", "\163\171\156\143", "\77", "\41", "\144\145\154\141\171\141\142\154\145", 
"\145\141\147\145\162", "\154\141\172\171", "\144\157", "\51", "\50", "\72\75", null, null, null, null, 
"\73", "\54", "\72", "\173", "\174", "\175", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x7e7fffffffffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[17];
private final int[] jjstateSet = new int[34];
protected char curChar;
/** Constructor. */
public TranslationUnitTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public TranslationUnitTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 17; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
