id     = "DRIVER"
name   = "Driver"
header = "options/main_options.h"

[[option]]
  name       = "version"
  category   = "common"
  short      = "V"
  long       = "version"
  type       = "bool"
  read_only  = true
  alternate  = false
  help       = "identify this CVC4 binary"

[[option]]
  name       = "help"
  category   = "common"
  short      = "h"
  long       = "help"
  type       = "bool"
  read_only  = true
  alternate  = false
  help       = "full command line reference"

[[option]]
  category   = "common"
  long       = "show-config"
  type       = "void"
  handler    = "showConfiguration"
  read_only  = true
  help       = "show CVC4 static configuration"

[[option]]
  category   = "common"
  long       = "copyright"
  type       = "void"
  handler    = "copyright"
  read_only  = true
  help       = "show CVC4 copyright information"

[[option]]
  name       = "seed"
  category   = "common"
  short      = "s"
  long       = "seed=N"
  type       = "uint64_t"
  default    = "0"
  read_only  = true
  help       = "seed for random number generator"

[[option]]
  category   = "regular"
  long       = "show-debug-tags"
  type       = "void"
  handler    = "showDebugTags"
  read_only  = true
  help       = "show all available tags for debugging"

[[option]]
  category   = "regular"
  long       = "show-trace-tags"
  type       = "void"
  handler    = "showTraceTags"
  read_only  = true
  help       = "show all available tags for tracing"

[[option]]
  name       = "earlyExit"
  category   = "expert"
  long       = "early-exit"
  type       = "bool"
  default    = "true"
  read_only  = true
  help       = "do not run destructors at exit; default on except in debug builds"

[[option]]
  name       = "interactive"
  category   = "regular"
  long       = "interactive"
  type       = "bool"
  help       = "force interactive/non-interactive mode"

[[option]]
  name       = "interactivePrompt"
  category   = "undocumented"
  long       = "interactive-prompt"
  type       = "bool"
  default    = "true"
  read_only  = true
  help       = "interactive prompting while in interactive mode"

[[option]]
  name       = "segvSpin"
  category   = "regular"
  long       = "segv-spin"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "spin on segfault/other crash waiting for gdb"

[[option]]
  name       = "tearDownIncremental"
  category   = "expert"
  long       = "tear-down-incremental=N"
  type       = "int"
  default    = "0"
  read_only  = true
  help       = "implement PUSH/POP/multi-query by destroying and recreating SmtEngine every N queries"
