id     = "SETS"
name   = "Sets"
header = "options/sets_options.h"

[[option]]
  name       = "setsProxyLemmas"
  category   = "regular"
  long       = "sets-proxy-lemmas"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "introduce proxy variables eagerly to shorten lemmas"

[[option]]
  name       = "setsInferAsLemmas"
  category   = "regular"
  long       = "sets-infer-as-lemmas"
  type       = "bool"
  default    = "true"
  read_only  = true
  help       = "send inferences as lemmas"

[[option]]
  name       = "setsExt"
  category   = "regular"
  long       = "sets-ext"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "enable extended symbols such as complement and universe in theory of sets"
